# Generated by Django 5.0.1 on 2024-02-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cost_per_item', models.DecimalField(decimal_places=2, default='0.0', max_digits=19)),
                ('quantity_in_stock', models.IntegerField(default='0')),
                ('quantity_sold', models.IntegerField(default='0')),
                ('sales', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('last_sales_date', models.DateField(auto_now=True)),
                ('cost_sold_per_item', models.DecimalField(decimal_places=2, default='0.0', max_digits=19)),
                ('reorder_level', models.IntegerField(default='0', null=True)),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default='0', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.category')),
            ],
        ),
    ]
