# Generated by Django 5.0.1 on 2024-03-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_inventory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='review_rate',
            new_name='rating',
        ),
    ]
